#!/usr/bin/env python3
from __future__ import annotations

import argparse
import contextlib
import io
import json
import os
import secrets
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Mapping, Sequence

import harness_bootstrap_wizard
import harness_controller
import harness_env
import harness_export
import harness_loop
import harness_profiles
import harness_starter_install
from harness_autonomy.relay import normalize_relay_repo_id


ENV_GENERATED_HEADER = "# Generated by ./harness. Do not commit this file."
RECOVERY_VIEW_PATHS = ("CURRENT_STATE.md", "RUNS_INDEX.md", "SESSION_BOOTSTRAP.md")
GLOBAL_SHIM_MARKER = "HARNESS_GLOBAL_SHIM_V1"
DEFAULT_GLOBAL_SHIM_DIR = Path("~/.local/bin")
UNSAFE_GLOBAL_SHIM_DIRS = (
    Path("/bin"),
    Path("/sbin"),
    Path("/usr/bin"),
    Path("/usr/sbin"),
    Path("/usr/local/bin"),
    Path("/opt/homebrew/bin"),
)


class HarnessCliError(RuntimeError):
    pass


@dataclass(frozen=True)
class CommandResult:
    target_root: Path
    receipt: Path | None
    wizard_run: Path | None
    env_path: Path | None
    applied: bool
    profile: str


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _clean_git_env() -> dict[str, str]:
    env = dict(os.environ)
    for key in tuple(env):
        if key.startswith("GIT_"):
            env.pop(key, None)
    return env


def _git(args: Sequence[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        check=False,
        text=True,
        capture_output=True,
        env=_clean_git_env(),
    )


def _git_checked(args: Sequence[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    result = _git(args, cwd=cwd)
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise HarnessCliError(f"git {' '.join(args)} failed: {detail}")
    return result


def _target_path(raw: Path) -> Path:
    if raw.is_absolute():
        return raw.resolve()
    return (Path.cwd() / raw).resolve()


def _selected_profile(args: argparse.Namespace) -> str:
    if getattr(args, "no_telegram", False):
        return harness_profiles.PROFILE_MINIMAL
    profile = str(getattr(args, "profile", harness_profiles.DEFAULT_PROFILE) or harness_profiles.DEFAULT_PROFILE)
    if profile not in harness_profiles.PROFILE_REGISTRY:
        raise HarnessCliError(f"unknown profile: {profile}")
    return profile


def _profile_enables_telegram(profile: str) -> bool:
    return harness_profiles.profile_enables_telegram(profile)


def _default_answers(name: str) -> dict[str, object]:
    return {
        "product_name": name,
        "product_goal": f"Build {name} with harness-guided automation.",
        "primary_users": "operator",
        "main_paths": ["src/**", "tests/**"],
        "validation_command": "python3 -m pytest -q",
        "first_goal_active": False,
    }


def _temporary_answers_file(name: str) -> tempfile.NamedTemporaryFile[str]:
    handle = tempfile.NamedTemporaryFile("w", encoding="utf-8", suffix="-harness-answers.json", delete=False)
    json.dump(_default_answers(name), handle, ensure_ascii=False, indent=2, sort_keys=True)
    handle.write("\n")
    handle.flush()
    return handle


def _wizard_answers_path(args: argparse.Namespace, name: str) -> tuple[Path | None, tempfile.NamedTemporaryFile[str] | None]:
    if getattr(args, "no_wizard", False):
        return None, None
    answers = getattr(args, "answers", None)
    if answers is not None:
        return answers.resolve(), None
    temp_file = _temporary_answers_file(name)
    return Path(temp_file.name), temp_file


def _validate_answers_file(answers_path: Path | None) -> None:
    if answers_path is None:
        return
    if not answers_path.exists():
        raise HarnessCliError(f"bootstrap answers file not found: {answers_path.as_posix()}")
    try:
        payload = json.loads(answers_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HarnessCliError(f"bootstrap answers file is not valid JSON: {answers_path.as_posix()}") from exc
    if not isinstance(payload, dict):
        raise HarnessCliError("bootstrap answers file must contain a JSON object")
    try:
        harness_bootstrap_wizard.collect_interview(payload)
    except (TypeError, ValueError, KeyError) as exc:
        raise HarnessCliError(f"bootstrap answers file is not a valid starter interview: {answers_path.as_posix()}") from exc


def _preflight_target_env(target_root: Path, *, profile: str) -> None:
    tracked_env = _tracked_env_files(target_root)
    if tracked_env:
        raise HarnessCliError("tracked env files must be untracked before installing harness: " + ", ".join(tracked_env))
    generated_env = target_root / ".env.harness.generated"
    if generated_env.exists() or generated_env.is_symlink():
        raise HarnessCliError("refusing to reuse existing env file: .env.harness.generated")
    if not _profile_enables_telegram(profile):
        return
    destination = _env_destination(target_root)
    if destination.exists() or destination.is_symlink():
        raise HarnessCliError(f"refusing to overwrite existing env file: {destination.name}")


def _commit_path_if_dirty(target_root: Path, path: Path, message: str) -> None:
    relative = path.resolve().relative_to(target_root.resolve()).as_posix()
    status = _git(["status", "--porcelain=v1", "--", relative], cwd=target_root)
    if status.returncode != 0:
        raise HarnessCliError("unable to inspect bootstrap wizard git status")
    if not status.stdout.strip():
        return
    _git_checked(["add", relative], cwd=target_root)
    _git_checked(["commit", "-m", message], cwd=target_root)


def _commit_paths_if_dirty(target_root: Path, paths: Sequence[str], message: str) -> None:
    status = _git(["status", "--porcelain=v1", "--", *paths], cwd=target_root)
    if status.returncode != 0:
        raise HarnessCliError("unable to inspect generated recovery view git status")
    if not status.stdout.strip():
        return
    _git_checked(["add", *paths], cwd=target_root)
    _git_checked(["commit", "-m", message], cwd=target_root)


def _sync_recovery_views(target_root: Path) -> None:
    result = subprocess.run(
        [sys.executable, "scripts/harness_loop.py", "sync-state"],
        cwd=target_root,
        check=False,
        text=True,
        capture_output=True,
        env=_clean_git_env(),
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise HarnessCliError(f"recovery sync failed: {detail}")
    _commit_paths_if_dirty(target_root, RECOVERY_VIEW_PATHS, "chore: sync harness recovery state")


def _repo_id_for(target_root: Path) -> str:
    return normalize_relay_repo_id(target_root.name)


def _strong_signing_key() -> str:
    return secrets.token_urlsafe(48)


def _env_destination(target_root: Path) -> Path:
    dotenv = target_root / ".env"
    if not dotenv.exists():
        return dotenv
    return target_root / ".env.harness.generated"


def _write_telegram_env(target_root: Path) -> Path:
    destination = _env_destination(target_root)
    if destination.exists():
        raise HarnessCliError(f"refusing to overwrite existing env file: {destination.name}")
    if destination.is_symlink():
        raise HarnessCliError(f"refusing to write env through symlink: {destination.name}")
    signing_key = _strong_signing_key()
    lines = [
        ENV_GENERATED_HEADER,
        f"# Created: {datetime.now().isoformat(timespec='seconds')}",
        "",
        "HARNESS_TELEGRAM_BRIDGE_ENABLED=true",
        "# HARNESS_TELEGRAM_BOT_TOKEN=<bot-token>",
        "# HARNESS_TELEGRAM_ADMIN_CHAT_ID=<admin-chat-id>",
        "# HARNESS_TELEGRAM_OPERATOR_USER_IDS=<telegram-numeric-user-id>",
        "",
        "HARNESS_RELAY_ENABLED=true",
        f"HARNESS_RELAY_REPO_ID={_repo_id_for(target_root)}",
        f"HARNESS_RELAY_SIGNING_KEY={signing_key}",
        "HARNESS_RELAY_TTL_SECONDS=604800",
        "# UPSTASH_REDIS_REST_URL=<upstash-rest-url>",
        "# UPSTASH_REDIS_REST_TOKEN=<upstash-rest-token>",
        "",
    ]
    destination.write_text("\n".join(lines), encoding="utf-8")
    return destination


def _start_wizard_for_existing_repo(
    *,
    source_root: Path,
    target_root: Path,
    answers_path: Path | None,
) -> Path | None:
    if answers_path is None:
        return None
    command = [
        sys.executable,
        str(source_root / "scripts" / "harness_bootstrap_wizard.py"),
        "start",
        "--target",
        str(target_root),
        "--answers",
        str(answers_path),
    ]
    result = subprocess.run(command, check=False, text=True, capture_output=True, env=_clean_git_env())
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise HarnessCliError(f"bootstrap wizard start failed: {detail}")
    output = result.stdout.strip().splitlines()
    return Path(output[-1]).resolve() if output else None


def command_new(args: argparse.Namespace) -> int:
    source_root = repo_root()
    target = _target_path(args.target)
    name = args.name or target.name
    profile = _selected_profile(args)
    answers_path, temp_answers = _wizard_answers_path(args, name)
    try:
        _validate_answers_file(answers_path)
        result = harness_starter_install.create_project(
            source_root=source_root,
            target=target,
            name=name,
            apply=not args.dry_run,
            include_policy=args.include_policy,
            telegram_operator_bridge=_profile_enables_telegram(profile),
            force_existing=args.force_existing,
            start_wizard=answers_path is not None,
            wizard_answers=answers_path,
        )
        env_path: Path | None = None
        if result.applied and result.wizard_run is not None:
            _commit_path_if_dirty(result.target_root, result.wizard_run, "chore: start harness bootstrap interview")
        if result.applied:
            _sync_recovery_views(result.target_root)
        if result.applied and _profile_enables_telegram(profile):
            env_path = _write_telegram_env(result.target_root)
        _print_completion(
            CommandResult(
                target_root=result.target_root,
                receipt=result.install_receipt,
                wizard_run=result.wizard_run,
                env_path=env_path,
                applied=result.applied,
                profile=profile,
            )
        )
        return 0
    except harness_starter_install.InstallerError as exc:
        print(f"error: {exc}")
        return 2
    except HarnessCliError as exc:
        print(f"error: {exc}")
        return 2
    finally:
        if temp_answers is not None:
            temp_name = temp_answers.name
            temp_answers.close()
            Path(temp_name).unlink(missing_ok=True)


def command_init(args: argparse.Namespace) -> int:
    source_root = repo_root()
    target_root = _target_path(args.target)
    name = args.name or target_root.name
    profile = _selected_profile(args)
    answers_path, temp_answers = _wizard_answers_path(args, name)
    try:
        _validate_answers_file(answers_path)
        validated = harness_starter_install.validate_target(source_root, target_root)
        _preflight_target_env(validated, profile=profile)
        plan = harness_starter_install.build_install_plan(
            source_root=source_root,
            target_root=validated,
            include_policy=args.include_policy,
            telegram_operator_bridge=_profile_enables_telegram(profile),
            force_existing=args.force_existing,
        )
        if plan.conflicts:
            print(harness_starter_install.render_plan(plan), end="")
            return 2
        receipt: Path | None = None
        wizard_run: Path | None = None
        env_path: Path | None = None
        if not args.dry_run:
            receipt = harness_starter_install.apply_install_plan(plan)
            wizard_run = _start_wizard_for_existing_repo(
                source_root=source_root,
                target_root=validated,
                answers_path=answers_path,
            )
            if _profile_enables_telegram(profile):
                env_path = _write_telegram_env(validated)
        else:
            print(harness_starter_install.render_plan(plan), end="")
        _print_completion(
            CommandResult(
                target_root=validated,
                receipt=receipt,
                wizard_run=wizard_run,
                env_path=env_path,
                applied=not args.dry_run,
                profile=profile,
            )
        )
        return 0
    except harness_starter_install.InstallerError as exc:
        print(f"error: {exc}")
        return 2
    except HarnessCliError as exc:
        print(f"error: {exc}")
        return 2
    finally:
        if temp_answers is not None:
            temp_name = temp_answers.name
            temp_answers.close()
            Path(temp_name).unlink(missing_ok=True)


def _print_completion(result: CommandResult) -> None:
    print("하네스 스타터 준비 완료")
    print(f"- 프로젝트: `{result.target_root.as_posix()}`")
    print(f"- 프로파일: `{result.profile}`")
    print(f"- 적용됨: `{str(result.applied).lower()}`")
    print("- live state 복사: `no`")
    print("- 장기 루프 시작: `no`")
    if result.receipt is not None:
        print(f"- 설치 receipt: `{result.receipt.as_posix()}`")
    if result.wizard_run is not None:
        print(f"- bootstrap interview: `{result.wizard_run.as_posix()}`")
    if result.env_path is not None:
        print(f"- env 파일: `{result.env_path.as_posix()}` (secret 값은 출력하지 않음)")
    print("")
    next_command = "./harness complete-setup --apply" if result.wizard_run is not None else "./harness verify"
    print(f"다음 명령: `cd {result.target_root.as_posix()} && {next_command}`")


def _tracked_env_files(target_root: Path) -> list[str]:
    result = _git(["ls-files", ".env", ".env.*"], cwd=target_root)
    if result.returncode != 0:
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip() and line.strip() != ".env.example"]


def _verify_required_files(target_root: Path) -> list[str]:
    required = [
        "harness",
        "HARNESS.md",
        "scripts/harness_starter_install.py",
        "scripts/harness_cli.py",
        "scripts/harness_autonomy/relay.py",
        "scripts/harness_telegram_bridge.py",
        "docs/harness/START_HERE.md",
        "backlog/README.md",
    ]
    return [path for path in required if not (target_root / path).exists()]


def _has_executable_backlog(target_root: Path) -> bool:
    items = harness_loop.discover_backlog_items(target_root)
    return any(item.status == "queued" and item.autonomy_execute == "auto" for item in items)


def _bootstrap_approved(target_root: Path) -> bool:
    for path in (target_root / "runs" / "harness").glob("*/approval-receipt.json"):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if payload.get("apply") is True:
            return True
    return False


def _docs_ready(target_root: Path) -> dict[str, bool]:
    paths = {
        "prd": Path("docs/PRD.md"),
        "architecture": Path("docs/ARCHITECTURE.md"),
        "adr": Path("docs/ADR.md"),
        "goals": Path("docs/harness/GOALS.md"),
    }
    return {key: (target_root / path).exists() and bool((target_root / path).read_text(encoding="utf-8").strip()) for key, path in paths.items()}


def _build_verify_payload(target_root: Path, *, loop_ready: bool) -> dict[str, object]:
    missing = _verify_required_files(target_root)
    status = _git(["status", "--porcelain=v1"], cwd=target_root)
    dirty = status.stdout.strip().splitlines() if status.returncode == 0 else ["<unable to inspect>"]
    tracked_env = _tracked_env_files(target_root)
    env_values = harness_env.read_harness_env_files(target_root, include_process_env=True)
    telegram_ready = harness_env.telegram_relay_readiness(env_values)
    docs_ready = _docs_ready(target_root)
    executable_backlog = _has_executable_backlog(target_root)
    bootstrap_approved = _bootstrap_approved(target_root)
    blockers: list[str] = []
    if missing:
        blockers.append("required-files-missing")
    if dirty:
        blockers.append("git-dirty")
    if tracked_env:
        blockers.append("tracked-env-files")
    if loop_ready and not bootstrap_approved:
        blockers.append("bootstrap-not-applied")
    if loop_ready and not all(docs_ready.values()):
        blockers.append("bootstrap-docs-missing")
    if loop_ready and not executable_backlog:
        blockers.append("no-executable-backlog")
    return {
        "schema_version": 1,
        "target": target_root.as_posix(),
        "mode": "loop-ready" if loop_ready else "install",
        "ok": not blockers,
        "blockers": blockers,
        "required_files": {"ok": not missing, "missing": missing},
        "git": {"clean": not dirty, "dirty_paths": dirty},
        "tracked_env_files": tracked_env,
        "telegram_relay": telegram_ready,
        "telegram_relay_live_ready": all(telegram_ready.values()),
        "bootstrap": {
            "approved": bootstrap_approved,
            "docs_ready": docs_ready,
            "executable_backlog": executable_backlog,
        },
    }


def _next_verify_command(payload: Mapping[str, object], *, loop_ready: bool) -> str:
    blockers = set(payload.get("blockers") or [])
    if "git-dirty" in blockers or "tracked-env-files" in blockers:
        return "git status --short"
    if "bootstrap-not-applied" in blockers or "bootstrap-docs-missing" in blockers or "no-executable-backlog" in blockers:
        return "./harness complete-setup --apply"
    if "required-files-missing" in blockers:
        return "./harness verify"
    return "./harness run --once" if loop_ready else "./harness verify --loop-ready"


def _render_verify_text(payload: Mapping[str, object], *, loop_ready: bool) -> None:
    required = payload["required_files"]
    git_state = payload["git"]
    bootstrap = payload["bootstrap"]
    telegram = payload["telegram_relay"]
    print("하네스 검증")
    print(f"- 대상: `{payload['target']}`")
    print(f"- 결과: {'준비됨' if payload['ok'] else '준비 필요'}")
    print(f"- 필수 파일: {'ok' if required['ok'] else 'missing ' + ', '.join(required['missing'])}")
    print(f"- git clean: {'yes' if git_state['clean'] else 'no'}")
    tracked_env = payload["tracked_env_files"]
    print(f"- tracked env 파일: {'none' if not tracked_env else ', '.join(tracked_env)}")
    if loop_ready:
        docs_ready = bootstrap["docs_ready"]
        missing_docs = [name for name, ok in docs_ready.items() if not ok]
        print(f"- bootstrap 적용: {'yes' if bootstrap['approved'] else 'no'}")
        print(f"- bootstrap 문서: {'ok' if not missing_docs else 'missing ' + ', '.join(missing_docs)}")
        print(f"- 실행 가능한 backlog: {'yes' if bootstrap['executable_backlog'] else 'no'}")
    relay_missing = [key for key, ok in telegram.items() if not ok]
    print(
        f"- Telegram/Redis 알림(선택): "
        f"{'live-ready' if not relay_missing else 'loop 실행에는 필수 아님; missing ' + ', '.join(relay_missing)}"
    )
    print(f"다음 명령: `{_next_verify_command(payload, loop_ready=loop_ready)}`")


def command_verify(args: argparse.Namespace) -> int:
    target = _target_path(args.target)
    try:
        target_root = harness_starter_install._git_toplevel(target)
    except harness_starter_install.InstallerError as exc:
        print(f"error: {exc}")
        return 2
    payload = _build_verify_payload(target_root, loop_ready=args.loop_ready)
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        _render_verify_text(payload, loop_ready=args.loop_ready)
    return 0 if payload["ok"] else 2


def _latest_bootstrap_run(target_root: Path) -> Path:
    runs_root = target_root / "runs" / "harness"
    candidates = [
        path
        for path in runs_root.glob("*")
        if path.is_dir() and (path / "bootstrap-interview.json").exists()
    ]
    if not candidates:
        raise HarnessCliError("bootstrap interview run 이 없습니다. 먼저 ./harness new/init 을 --no-wizard 없이 실행하세요.")
    return max(candidates, key=lambda path: (path.stat().st_mtime, path.name)).resolve()


def _resolve_bootstrap_run(target_root: Path, raw_run: Path | None) -> Path:
    run_dir = _latest_bootstrap_run(target_root) if raw_run is None else _target_path(raw_run)
    try:
        run_dir.resolve().relative_to((target_root / "runs" / "harness").resolve())
    except ValueError as exc:
        raise HarnessCliError("bootstrap run must be inside target runs/harness") from exc
    if not (run_dir / "bootstrap-interview.json").exists():
        raise HarnessCliError(f"missing bootstrap interview: {run_dir.as_posix()}")
    return run_dir.resolve()


def _starter_placeholder_templates(target_root: Path) -> dict[Path, str]:
    try:
        version = harness_export.read_current_version(target_root)
    except (OSError, ValueError) as exc:
        raise HarnessCliError("unable to read installed harness version before bootstrap apply") from exc
    return harness_export.build_starter_generated_templates(version)


def _render_bootstrap_drafts(run_dir: Path) -> Path:
    interview = harness_bootstrap_wizard._load_interview(run_dir)
    drafts_dir = harness_bootstrap_wizard.write_drafts(run_dir, harness_bootstrap_wizard.build_drafts(interview))
    return drafts_dir


def _bootstrap_manifest_paths(run_dir: Path) -> list[Path]:
    manifest_path = run_dir / "bootstrap-drafts-manifest.json"
    if not manifest_path.exists():
        raise HarnessCliError("bootstrap drafts manifest missing after render")
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    files = payload.get("files")
    if not isinstance(files, list):
        raise HarnessCliError("invalid bootstrap drafts manifest")
    return [Path(str(item.get("path") or "")) for item in files]


def _preflight_bootstrap_overwrites(target_root: Path, run_dir: Path, *, force_existing: bool) -> None:
    if force_existing:
        return
    templates = _starter_placeholder_templates(target_root)
    conflicts: list[str] = []
    for relative_path in _bootstrap_manifest_paths(run_dir):
        destination = target_root / relative_path
        if not destination.exists():
            continue
        if relative_path in templates and destination.read_text(encoding="utf-8", errors="replace") == templates[relative_path]:
            continue
        conflicts.append(relative_path.as_posix())
    if conflicts:
        raise HarnessCliError(
            "bootstrap apply would overwrite non-placeholder files; pass --force-existing after reviewing: "
            + ", ".join(conflicts)
        )


def _commit_bootstrap_outputs(target_root: Path, run_dir: Path) -> None:
    relative_run = run_dir.relative_to(target_root.resolve()).as_posix()
    paths = (
        relative_run,
        "docs/PRD.md",
        "docs/ARCHITECTURE.md",
        "docs/ADR.md",
        "docs/harness/GOALS.md",
        "backlog/queued",
    )
    _commit_paths_if_dirty(target_root, paths, "chore: complete harness bootstrap")


def command_complete_setup(args: argparse.Namespace) -> int:
    target = _target_path(args.target)
    try:
        target_root = harness_starter_install._git_toplevel(target)
        run_dir = _resolve_bootstrap_run(target_root, args.run)
        drafts_dir = _render_bootstrap_drafts(run_dir)
        if not args.apply:
            print("bootstrap draft 생성 완료")
            print(f"- run: `{run_dir.as_posix()}`")
            print(f"- drafts: `{drafts_dir.as_posix()}`")
            print("다음 명령: `./harness complete-setup --apply`")
            return 0
        _preflight_bootstrap_overwrites(target_root, run_dir, force_existing=args.force_existing)
        receipt = harness_bootstrap_wizard.approve_drafts(
            run_dir=run_dir,
            target=target_root,
            apply=True,
            force_existing=True,
        )
        if not args.no_commit:
            _commit_bootstrap_outputs(target_root, run_dir)
            _sync_recovery_views(target_root)
        print("bootstrap 적용 완료")
        print(f"- run: `{run_dir.as_posix()}`")
        print(f"- approval receipt: `{receipt.as_posix()}`")
        print(f"- commit: `{'no' if args.no_commit else 'yes'}`")
        print("다음 명령: `./harness verify --loop-ready`")
        return 0
    except (harness_starter_install.InstallerError, harness_bootstrap_wizard.WizardError, HarnessCliError) as exc:
        print(f"error: {exc}")
        return 2


def _run_existing_script(script_name: str, args: Sequence[str]) -> int:
    root = repo_root()
    command = [sys.executable, str(root / "scripts" / script_name), *args]
    result = subprocess.run(command, cwd=root, check=False, env=_clean_git_env())
    return result.returncode


def command_status(args: argparse.Namespace) -> int:
    forwarded = ["status"]
    if args.json:
        forwarded.append("--json")
    forwarded.extend(args.extra)
    return _run_existing_script("harness_autonomy.py", forwarded)


def command_dashboard(args: argparse.Namespace) -> int:
    root = repo_root()
    for relative in (
        Path("reports/harness-autonomy/operator-dashboard-latest.md"),
        Path("reports/harness-autonomy/operator-dashboard-latest.html"),
    ):
        path = root / relative
        state = "exists" if path.exists() else "missing"
        print(f"- {relative.as_posix()}: {state}")
    return 0


def command_run(args: argparse.Namespace) -> int:
    if not args.once:
        print("error: starter 실행은 bounded smoke 만 허용합니다. --once 를 붙이세요.")
        print("다음 명령: `./harness run --once`")
        return 2
    try:
        target_root = harness_starter_install._git_toplevel(Path.cwd())
    except harness_starter_install.InstallerError as exc:
        print(f"error: {exc}")
        return 2
    payload = _build_verify_payload(target_root, loop_ready=True)
    if not payload["ok"]:
        _render_verify_text(payload, loop_ready=True)
        print("run --once 중단: 위 blocker를 먼저 해결해야 합니다.")
        return 2
    extra = list(args.extra)
    if extra[:1] == ["--"]:
        extra = extra[1:]
    return _run_existing_script(
        "harness_autonomy.py",
        ["run-once", "--mode", "auto", "--runner", "codex", "--runner-model", "auto", "--git-backup", "off", *extra],
    )


def command_export(args: argparse.Namespace) -> int:
    command = ["--starter-bundle", str(args.output_dir)]
    if args.force:
        command.append("--force")
    return _run_existing_script("harness_export.py", command)


def command_upgrade(args: argparse.Namespace) -> int:
    source_root = _target_path(args.source)
    target = _target_path(args.target)
    try:
        target_root = harness_starter_install.validate_target(source_root, target)
        tracked_env = _tracked_env_files(target_root)
        if tracked_env:
            raise HarnessCliError("tracked env files must be untracked before upgrading harness: " + ", ".join(tracked_env))
        plan = harness_starter_install.build_upgrade_plan(
            source_root=source_root,
            target_root=target_root,
            force_existing=args.force_existing,
        )
        if args.json and not args.apply:
            print(harness_starter_install.render_upgrade_plan(plan, as_json=True), end="")
        elif not args.apply or plan.conflicts:
            print(harness_starter_install.render_upgrade_plan(plan), end="")
        if plan.conflicts:
            return 2
        if not args.apply:
            return 0
        receipt = harness_starter_install.apply_upgrade_plan(plan)
        if args.json:
            payload = {
                "schema_version": 1,
                "applied": True,
                "apply_required": bool(plan.operations),
                "noop": not plan.operations,
                "receipt_written": True,
                "target": target_root.as_posix(),
                "receipt": receipt.as_posix(),
                "updated_files": len(plan.operations),
                "skipped_files": len(plan.skipped),
                "next_command": "git status --short",
                "after_review_command": "./harness verify --loop-ready",
            }
            print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        else:
            print("하네스 스타터 업그레이드 적용 완료")
            print(f"- 대상: `{target_root.as_posix()}`")
            print(f"- 갱신 파일: {len(plan.operations)}")
            print(f"- receipt: `{receipt.as_posix()}`")
            print("- long-running loop 시작: `no`")
            print("다음 명령: `git status --short`")
            print("검토/커밋 후: `./harness verify --loop-ready`")
            print("아직 bootstrap 전이면 먼저 `./harness complete-setup --apply` 를 실행하세요.")
        return 0
    except (harness_starter_install.InstallerError, HarnessCliError) as exc:
        print(f"error: {exc}")
        return 2


def _env_command_root() -> Path:
    try:
        return harness_starter_install._git_toplevel(Path.cwd())
    except harness_starter_install.InstallerError:
        return Path.cwd().resolve()


def _state_lists(entries: Sequence[Mapping[str, str]]) -> dict[str, list[str]]:
    states = {"present": [], "missing": [], "weak": []}
    for entry in entries:
        state = str(entry.get("state") or "")
        key = str(entry.get("key") or "")
        if state in states and key:
            states[state].append(key)
    return states


def _render_env_check_text(payload: Mapping[str, object]) -> None:
    states = _state_lists(payload["entries"])  # type: ignore[arg-type]
    counts = payload["counts"]
    print(f"하네스 env check: {payload['provider_label']}")
    print(f"- 결과: {'로컬 env 입력 준비됨' if payload['ok'] else '로컬 env 보강 필요'}")
    print("- 원격 검증: 실행 안 함")
    print(f"- 상태: present {counts['present']}, missing {counts['missing']}, weak {counts['weak']}")
    print("- 값 출력: no")
    if states["missing"]:
        print(f"- 누락: {', '.join(states['missing'])}")
    if states["weak"]:
        print(f"- 보강 필요: {', '.join(states['weak'])}")
    for index, action in enumerate(payload["next_actions_ko"], start=1):  # type: ignore[index]
        print(f"- 다음 조치 {index}: {action}")


def _render_env_register_text(payload: Mapping[str, object]) -> None:
    counts = payload["counts"]
    actions = payload["actions"]
    print(f"하네스 env register dry-run: {payload['provider_label']}")
    print("- 원격 변경: 실행 안 함")
    print("- apply 지원: no")
    print(f"- 상태: present {counts['present']}, missing {counts['missing']}, weak {counts['weak']}")
    print(f"- 계획 항목: {len(actions)}")
    print("- 값 출력: no")
    print(f"- 요약: {payload['summary_ko']}")
    for action in actions[:12]:
        key = action.get("key", "")
        state = action.get("state", "")
        targets = action.get("targets")
        target_suffix = f" -> {', '.join(targets)}" if isinstance(targets, list) and targets else ""
        print(f"- 계획: {key} ({state}){target_suffix}")
    for index, action in enumerate(payload["next_actions_ko"], start=1):  # type: ignore[index]
        print(f"- 다음 조치 {index}: {action}")


def command_env_check(args: argparse.Namespace) -> int:
    target_root = _env_command_root()
    values = harness_env.read_harness_env_files(target_root, include_process_env=True)
    try:
        payload = harness_env.build_provider_env_report(values, args.provider)
    except ValueError as exc:
        print(f"error: {exc}")
        return 2
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        _render_env_check_text(payload)
    return 0 if payload["ok"] else 2


def command_env_register(args: argparse.Namespace) -> int:
    if not args.dry_run:
        print("error: env register 는 현재 --dry-run 만 지원합니다. 원격 env apply 는 별도 run에서 승격하세요.")
        return 2
    target_root = _env_command_root()
    values = harness_env.read_harness_env_files(target_root, include_process_env=True)
    try:
        payload = harness_env.build_provider_register_dry_run(values, args.provider)
    except ValueError as exc:
        print(f"error: {exc}")
        return 2
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        _render_env_register_text(payload)
    return 0 if payload["ok"] else 2


def command_profiles(args: argparse.Namespace) -> int:
    if args.action == "show" and not args.profile_name:
        print("error: 프로파일 이름이 필요합니다")
        return 2
    if args.profile_name:
        try:
            profile = harness_profiles.get_profile(args.profile_name)
        except ValueError:
            print(f"error: 알 수 없는 프로파일: {args.profile_name}")
            return 2
        print(f"프로파일: `{profile.name}`")
        print(f"- Telegram/Redis 준비: {'예' if profile.telegram_operator_bridge else '아니오'}")
        print(f"- 설명: {profile.description_ko}")
        if profile.required_env_keys:
            print(f"- 생성/관리 env: {', '.join(profile.required_env_keys)}")
        if profile.optional_env_keys:
            print(f"- 운영자가 채울 env: {', '.join(profile.optional_env_keys)}")
        print(f"다음 명령: `{profile.recommended_next}`")
        return 0
    print("사용 가능한 하네스 프로파일")
    for name in harness_profiles.profile_names():
        profile = harness_profiles.get_profile(name)
        default_marker = " (기본값)" if name == harness_profiles.DEFAULT_PROFILE else ""
        print(f"- `{name}`{default_marker}: {profile.description_ko}")
    print("다음 명령: `./harness profiles show telegram`")
    return 0


def command_version(args: argparse.Namespace) -> int:
    root = repo_root()
    version = harness_export.read_current_version(root)
    missing = [path.as_posix() for path in harness_export.missing_starter_source_paths(root, version)]
    controller_missing = [path.as_posix() for path in harness_export.missing_controller_source_paths(root, version)]
    payload = {
        "schema_version": 1,
        "version": version,
        "source_root": root.as_posix(),
        "export_source_check": {"ok": not missing, "missing": missing},
        "controller_export_source_check": {"ok": not controller_missing, "missing": controller_missing},
    }
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        print(f"하네스 버전: `{version}`")
        print(f"- export source: {'ok' if not missing else 'missing ' + ', '.join(missing)}")
        print(
            "- controller export source: "
            f"{'ok' if not controller_missing else 'controller-only incomplete; missing ' + ', '.join(controller_missing)}"
        )
        print("다음 명령: `./harness verify`")
    return 0 if not missing else 2


def _controller_version() -> str:
    return harness_export.read_current_version(repo_root())


def _targets_ignored_by_git(root: Path) -> bool:
    result = _git(["check-ignore", "-q", "targets/"], cwd=root)
    return result.returncode == 0


def command_controller_export(args: argparse.Namespace) -> int:
    command = ["--controller-bundle", str(args.output_dir)]
    if args.force:
        command.append("--force")
    if args.sanitize_report is not None:
        command.extend(["--sanitize-report", str(args.sanitize_report)])
    return _run_existing_script("harness_export.py", command)


def command_controller_doctor(args: argparse.Namespace) -> int:
    root = repo_root()
    version = _controller_version()
    missing = [path.as_posix() for path in harness_export.missing_controller_source_paths(root, version)]
    records = harness_controller.list_targets(root)
    targets_ignored = _targets_ignored_by_git(root)
    payload = {
        "schema_version": 1,
        "controller_root": root.as_posix(),
        "version": version,
        "mode": "controller",
        "export_source_check": {"ok": not missing, "missing": missing},
        "targets_count": len(records),
        "targets_root": (root / "targets").as_posix(),
        "targets_ignored_by_git": targets_ignored,
    }
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        print("하네스 controller doctor")
        print(f"- controller root: `{root.as_posix()}`")
        print(f"- version: `{version}`")
        print(f"- export source: {'ok' if not missing else 'missing ' + ', '.join(missing)}")
        print(f"- registered targets: {len(records)}")
        print(f"- targets ignored by git: {'yes' if targets_ignored else 'no'}")
        print("- product repo 기본 정책: harness runtime 파일 커밋 안 함")
        print("- Telegram/Redis secret 위치: controller env only")
        print("다음 명령: `./harness target add <id> --repo /path/to/product-repo --branch main`")
    return 0 if not missing and targets_ignored else 2


def _load_controller_target(target_id: str) -> harness_controller.TargetRecord:
    return harness_controller.load_target(repo_root(), target_id)


def _resolve_controller_target(selector: str) -> harness_controller.TargetRecord:
    return harness_controller.resolve_target_selector(repo_root(), selector)


def _render_target_verify_text(payload: Mapping[str, object]) -> None:
    blockers = payload.get("blockers") or []
    warnings = payload.get("warnings") or []
    print("하네스 external target verify")
    print(f"- 대상: `{payload['target_id']}`")
    print(f"- product repo: `{payload['target_root']}`")
    print(f"- state root: `{payload['state_root']}`")
    print(f"- 결과: {'ready' if payload['ok'] else 'needs attention'}")
    print(f"- blockers: {', '.join(str(item) for item in blockers) if blockers else 'none'}")
    print(f"- warnings: {', '.join(str(item) for item in warnings) if warnings else 'none'}")
    print("- product repo harness 파일 쓰기: no")


def command_target_add(args: argparse.Namespace) -> int:
    try:
        record = harness_controller.add_target(
            controller_root=repo_root(),
            target_id=args.target_id,
            repo=_target_path(args.repo),
            branch=args.branch,
            controller_version=_controller_version(),
            profile=args.profile,
            display_name=args.display_name,
            force=args.force,
        )
        verification = harness_controller.verify_target(record)
        report = harness_controller.write_dashboard(
            controller_root=repo_root(),
            record=record,
            verification=verification,
        )
        if args.json:
            payload = {
                "schema_version": 1,
                "created": True,
                "target": record.to_json(repo_root()),
                "verification": verification,
                "dashboard": report.as_posix(),
            }
            print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        else:
            print("external target 등록 완료")
            print(f"- target: `{record.target_id}`")
            if record.display_name:
                print(f"- 표시 이름: `{record.display_name}`")
            print(f"- product repo: `{record.repo.as_posix()}`")
            print(f"- state root: `{record.state_root.as_posix()}`")
            print(f"- dashboard: `{report.as_posix()}`")
            print("- product repo 변경: no")
            if verification["blockers"]:
                print(f"- 확인 필요: {', '.join(verification['blockers'])}")
            print(f"다음 명령: `./harness target verify {record.target_id}`")
        return 0 if verification["ok"] else 2
    except harness_controller.ControllerError as exc:
        print(f"error: {exc}")
        return 2


def command_target_list(args: argparse.Namespace) -> int:
    records = harness_controller.list_targets(repo_root())
    if args.json:
        payload = {
            "schema_version": 1,
            "targets": [record.to_json(repo_root()) for record in records],
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        return 0
    print("등록된 external targets")
    if not records:
        print("- 대상 없음")
        print("다음 명령: `./harness target add <id> --repo /path/to/product-repo --branch main`")
        return 0
    for record in records:
        default_marker = " 기본 대상" if record.is_default else ""
        aliases = ", ".join("@" + alias for alias in record.aliases) if record.aliases else "별칭 없음"
        display = f" / {record.display_name}" if record.display_name else ""
        print(
            f"- 대상 ID `{record.target_id}`{display}: {record.repo.as_posix()} "
            f"({record.branch}; {aliases}{default_marker})"
        )
    return 0


def command_target_verify(args: argparse.Namespace) -> int:
    try:
        record = _resolve_controller_target(args.target)
        verification = harness_controller.verify_target(record)
        if args.json:
            print(json.dumps(verification, ensure_ascii=False, indent=2, sort_keys=True))
        else:
            _render_target_verify_text(verification)
        return 0 if verification["ok"] else 2
    except harness_controller.ControllerError as exc:
        print(f"error: {exc}")
        return 2


def command_target_status(args: argparse.Namespace) -> int:
    try:
        record = _resolve_controller_target(args.target)
        verification = harness_controller.verify_target(record)
        payload = {
            "schema_version": 1,
            "target": record.to_json(repo_root()),
            "verification": verification,
        }
        if args.json:
            print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        else:
            print("하네스 external target status")
            print(f"- 대상: `{record.target_id}`")
            print(f"- 상태: {'ready' if verification['ok'] else 'needs attention'}")
            print(f"- product repo: `{record.repo.as_posix()}`")
            print(f"- state root: `{record.state_root.as_posix()}`")
            print(f"- blockers: {', '.join(verification['blockers']) if verification['blockers'] else 'none'}")
            print(f"다음 명령: `./harness target dashboard {record.target_id}`")
        return 0 if verification["ok"] else 2
    except harness_controller.ControllerError as exc:
        print(f"error: {exc}")
        return 2


def command_target_dashboard(args: argparse.Namespace) -> int:
    try:
        record = _resolve_controller_target(args.target)
        verification = harness_controller.verify_target(record)
        report = harness_controller.write_dashboard(
            controller_root=repo_root(),
            record=record,
            verification=verification,
        )
        if args.json:
            print(json.dumps({"schema_version": 1, "dashboard": report.as_posix()}, ensure_ascii=False, indent=2))
        else:
            print("external target dashboard 갱신 완료")
            print(f"- 대상: `{record.target_id}`")
            print(f"- report: `{report.as_posix()}`")
        return 0
    except harness_controller.ControllerError as exc:
        print(f"error: {exc}")
        return 2


def _run_target_autonomy_state_plumbing(
    record: harness_controller.TargetRecord,
    *,
    lock: harness_controller.TargetRunLock,
    product_execution: bool = False,
    product_commit: bool = False,
    product_push: bool = False,
) -> subprocess.CompletedProcess[str]:
    root = repo_root()
    from harness_autonomy import AutonomyError, main as autonomy_main

    forwarded = [
        "--root",
        str(root),
        "--controller-root",
        str(root),
        "--target-id",
        record.target_id,
        "--target-root",
        str(record.repo),
        "--state-root",
        str(record.state_root),
        "--external-lock-owned",
        "--external-lock-token",
        lock.token,
    ]
    if product_execution:
        forwarded.append("--external-product-execution")
    if product_commit:
        forwarded.append("--external-product-commit")
    if product_push:
        forwarded.append("--external-product-push")
    forwarded.extend(
        [
            "run-once",
            "--mode",
            "auto",
            "--runner",
            "codex",
            "--runner-model",
            "auto",
            "--git-backup",
            "off",
        ]
    )
    stdout = io.StringIO()
    stderr = io.StringIO()
    with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
        try:
            returncode = autonomy_main(forwarded)
        except AutonomyError as exc:
            print(str(exc), file=stderr)
            returncode = 1
    command = ("harness_autonomy.py", *forwarded)
    return subprocess.CompletedProcess(command, returncode, stdout.getvalue(), stderr.getvalue())


def command_target_run(args: argparse.Namespace) -> int:
    if bool(args.once) == bool(args.execute_once):
        print("error: target run은 `--once` 또는 `--execute-once` 중 하나만 명시하세요.")
        return 2
    product_commit = bool(getattr(args, "commit", False))
    if product_commit and not bool(args.execute_once):
        print("error: `--commit`은 `--execute-once`와 함께만 사용할 수 있습니다.")
        return 2
    product_push = bool(getattr(args, "push", False))
    if product_push and not (bool(args.execute_once) and product_commit):
        print("error: `--push`는 `--execute-once --commit`과 함께만 사용할 수 있습니다.")
        return 2
    product_execution = bool(args.execute_once)
    lock: harness_controller.TargetRunLock | None = None
    try:
        record = _resolve_controller_target(args.target)
        lock = harness_controller.acquire_target_run_lock(
            controller_root=repo_root(),
            record=record,
            owner=f"pid:{os.getpid()}",
        )
        verification = harness_controller.verify_target(record)
        report = harness_controller.write_dashboard(
            controller_root=repo_root(),
            record=record,
            verification=verification,
        )
        run_blockers = harness_controller.target_run_blockers(verification)
        before_status = [
            str(line)
            for line in (
                verification.get("git", {}).get("dirty_paths", [])
                if isinstance(verification.get("git"), dict)
                else []
            )
        ]
        if run_blockers:
            smoke_report = harness_controller.write_target_run_smoke_report(
                controller_root=repo_root(),
                record=record,
                verification=verification,
                result="blocked",
                run_blockers=run_blockers,
                before_status=before_status,
                after_status=before_status,
                before_head="",
                after_head="",
                lock=lock,
                product_diff_execution="enabled" if product_execution else "disabled",
                product_commit_execution="enabled" if product_commit else "disabled",
                expected_product_paths=(
                    [harness_controller.PRODUCT_DIFF_SMOKE_FILE.as_posix()] if product_execution else []
                ),
                rollback_guidance=(
                    [harness_controller.product_diff_smoke_rollback_command(record.repo)]
                    if product_execution and not product_commit
                    else []
                ),
                product_push_execution="enabled" if product_push else "disabled",
            )
            _render_target_verify_text(verification)
            print("target run 중단: run blocker를 먼저 해결해야 합니다.")
            print(f"- run blockers: {', '.join(run_blockers)}")
            print(f"- smoke report: `{smoke_report.as_posix()}`")
            return 2
        before_head = harness_controller.target_git_head(record.repo)
        push_target: harness_controller.ProductPushTarget | None = None
        if product_push:
            push_target = harness_controller.resolve_product_diff_smoke_push_target(record.repo, record.branch)
            if push_target.remote_head != before_head:
                raise harness_controller.ControllerError(
                    "target push remote head does not match local HEAD; fetch/rebase before smoke push"
                )
        plumbing_result = _run_target_autonomy_state_plumbing(
            record,
            lock=lock,
            product_execution=product_execution,
            product_commit=product_commit,
            product_push=product_push,
        )
        after_status = harness_controller.target_git_status_lines(record.repo)
        after_head = harness_controller.target_git_head(record.repo)
        expected_after_status = (
            []
            if product_commit
            else harness_controller.product_diff_smoke_status_lines()
            if product_execution
            else before_status
        )
        head_changed = before_head != after_head
        product_commit_sha = after_head if product_commit and head_changed else ""
        product_commit_diff: list[str] = []
        product_push_sha = ""
        product_push_remote_after = ""
        product_push_error = ""
        post_verification = harness_controller.verify_target(record)
        post_markers = post_verification.get("harness_markers", [])
        post_blockers: list[str] = []
        if after_status != expected_after_status:
            post_blockers.append("target-git-status-changed")
        if product_commit:
            if not head_changed:
                post_blockers.append("target-head-not-advanced")
            else:
                try:
                    if harness_controller.target_git_parent(record.repo, "HEAD") != before_head:
                        post_blockers.append("target-head-parent-unexpected")
                    product_commit_diff = harness_controller.product_diff_smoke_commit_diff_lines(record.repo)
                except harness_controller.ControllerError as exc:
                    post_blockers.append(str(exc))
                expected_diff = [f"A\t{harness_controller.PRODUCT_DIFF_SMOKE_FILE.as_posix()}"]
                if product_commit_diff != expected_diff:
                    post_blockers.append("target-product-commit-diff-unexpected")
            if product_push and push_target is not None:
                try:
                    product_push_remote_after = harness_controller.target_remote_ref_head(
                        record.repo,
                        push_target.remote,
                        push_target.ref,
                    )
                except harness_controller.ControllerError as exc:
                    post_blockers.append(str(exc))
                else:
                    if product_push_remote_after == product_commit_sha:
                        product_push_sha = product_push_remote_after
                    elif plumbing_result.returncode == 0:
                        post_blockers.append("target-product-push-remote-head-unexpected")
                    elif product_push_remote_after != push_target.remote_head:
                        post_blockers.append("target-product-push-failed-after-remote-change")
                if plumbing_result.returncode != 0:
                    product_push_error = (plumbing_result.stderr or plumbing_result.stdout).strip()
        elif head_changed:
            post_blockers.append("target-head-changed")
        if post_markers:
            post_blockers.append("target-harness-files-present")
        if plumbing_result.returncode != 0:
            post_blockers.append("external-state-plumbing-failed")
        for blocker in harness_controller.target_run_blockers(post_verification):
            if product_execution and not product_commit and blocker == "target-git-dirty" and after_status == expected_after_status:
                continue
            if blocker not in post_blockers:
                post_blockers.append(blocker)
        rollback_guidance: list[str] = []
        if product_push and product_commit_sha:
            rollback_guidance.append(harness_controller.PRODUCT_DIFF_SMOKE_PUSH_CAUTION)
            rollback_guidance.append(
                "Local-only cleanup after remote recovery decision: "
                + harness_controller.product_diff_smoke_commit_rollback_command(record.repo, before_head)
            )
        elif product_commit and product_commit_sha:
            rollback_guidance.append(harness_controller.product_diff_smoke_commit_rollback_command(record.repo, before_head))
        elif product_commit:
            rollback_guidance.extend(harness_controller.product_diff_smoke_partial_rollback_commands(record.repo))
        elif product_execution:
            rollback_guidance.append(harness_controller.product_diff_smoke_rollback_command(record.repo))
        try:
            smoke_report = harness_controller.write_target_run_smoke_report(
                controller_root=repo_root(),
                record=record,
                verification=post_verification if post_blockers else verification,
                result="blocked" if post_blockers else "passed",
                run_blockers=post_blockers,
                before_status=before_status,
                after_status=after_status,
                before_head=before_head,
                after_head=after_head,
                lock=lock,
                product_diff_execution="enabled" if product_execution else "disabled",
                product_commit_execution="enabled" if product_commit else "disabled",
                product_commit_sha=product_commit_sha,
                product_push_execution="enabled" if product_push else "disabled",
                product_push_remote=push_target.remote if push_target else "",
                product_push_ref=push_target.ref if push_target else "",
                product_push_sha=product_push_sha,
                product_push_remote_before=push_target.remote_head if push_target else "",
                product_push_remote_after=product_push_remote_after,
                product_push_command=push_target.command if push_target else (),
                product_push_error=product_push_error[:500],
                expected_product_paths=(
                    [harness_controller.PRODUCT_DIFF_SMOKE_FILE.as_posix()] if product_execution else []
                ),
                product_commit_diff=product_commit_diff,
                rollback_guidance=rollback_guidance,
            )
        except harness_controller.ControllerError:
            if product_push and product_push_sha and push_target is not None:
                print("target run 후처리 실패: product smoke push는 이미 remote에 반영됐습니다.")
                print(f"- product push: {push_target.remote}/{record.branch} -> {product_push_sha}")
                print(f"- remote ref: {push_target.ref}")
                print(f"- 주의: {harness_controller.PRODUCT_DIFF_SMOKE_PUSH_CAUTION}")
            raise
        if post_blockers:
            print("target run 중단: product repo 상태가 예상과 다릅니다.")
            print(f"- run blockers: {', '.join(post_blockers)}")
            if product_push and product_push_sha and push_target is not None:
                print(f"- product push: {push_target.remote}/{record.branch} -> {product_push_sha}")
                print(f"- remote ref: {push_target.ref}")
                print(f"- 주의: {harness_controller.PRODUCT_DIFF_SMOKE_PUSH_CAUTION}")
            if plumbing_result.returncode != 0:
                detail = (plumbing_result.stderr or plumbing_result.stdout).strip()
                if detail:
                    print(f"- autonomy state plumbing: {detail[:300]}")
            print(f"- smoke report: `{smoke_report.as_posix()}`")
            return 2
        print("외부 target 상태 배관 점검 완료")
        print(f"- 대상 ID: `{record.target_id}`")
        print(f"- dashboard: `{report.as_posix()}`")
        print(f"- smoke report: `{smoke_report.as_posix()}`")
        print(f"- lock: acquired/released `{lock.path.as_posix()}`")
        print("- 검증 범위: target 등록/sidecar/dashboard/lock/product git 상태")
        if product_execution:
            print("- lane 실행: 시작 안 함")
            print("- 제품 변경 실행: 명시 opt-in smoke")
            print(f"- product diff: {harness_controller.PRODUCT_DIFF_SMOKE_FILE.as_posix()}")
            if product_commit:
                print(f"- product commit: {product_commit_sha}")
                if product_push and push_target is not None:
                    print(f"- product push: {push_target.remote}/{record.branch} -> {product_push_sha}")
                    print("- 주의: product remote branch가 갱신됐고 push-triggered automation이 실행될 수 있습니다.")
                    print(f"- 주의: {harness_controller.PRODUCT_DIFF_SMOKE_PUSH_CAUTION}")
                else:
                    print("- product push: 없음")
                    print("- 주의: product working tree 는 clean하지만 HEAD가 local smoke commit 1개 전진했습니다.")
                    print("- 주의: 이 smoke commit은 hooks/GPG signing을 건너뛰며 공유용 product commit이 아닙니다.")
            else:
                print("- product commit/push: 없음")
            if rollback_guidance:
                print(f"- rollback: `{rollback_guidance[0]}`")
                if product_commit and not product_push:
                    print(f"- rollback 주의: {harness_controller.PRODUCT_DIFF_SMOKE_COMMIT_ROLLBACK_CAUTION}")
        else:
            print("- lane 실행: 시작 안 함 (read-only/no-op smoke only)")
            print("- 제품 변경 실행: 비활성화")
            print("- autonomy state plumbing: sidecar 기록 완료")
            print("- product diff/commit/push: 없음")
            print("- 다음 단계: 제품 변경 smoke 는 `--execute-once` 명시 시에만 실행합니다.")
        print(f"- 다음 명령: `./harness target status {record.target_id}`")
        print(f"- 다음 명령: `./harness target dashboard {record.target_id}`")
        print(f"- product repo 변경: {'있음' if product_execution else '없음'}")
        return 0
    except harness_controller.ControllerError as exc:
        print(f"error: {exc}")
        return 2
    finally:
        if lock is not None:
            harness_controller.release_target_run_lock(lock)


def command_target_alias_add(args: argparse.Namespace) -> int:
    try:
        alias = harness_controller.validate_target_alias(args.alias)
        record = harness_controller.add_target_alias(repo_root(), args.target_id, alias)
        print("target alias 추가 완료")
        print(f"- 대상: `{record.target_id}`")
        print(f"- alias: `@{alias}`")
        print("- 저장/서명/락/인박스에는 canonical target id만 사용됩니다.")
        return 0
    except harness_controller.ControllerError as exc:
        print(f"error: {exc}")
        return 2


def command_target_alias_remove(args: argparse.Namespace) -> int:
    try:
        alias = harness_controller.validate_target_alias(args.alias)
        record = harness_controller.remove_target_alias(repo_root(), args.target_id, alias)
        print("target alias 제거 완료")
        print(f"- 대상: `{record.target_id}`")
        print(f"- alias: `@{alias}`")
        return 0
    except harness_controller.ControllerError as exc:
        print(f"error: {exc}")
        return 2


def command_target_alias_list(args: argparse.Namespace) -> int:
    records = harness_controller.list_targets(repo_root())
    if args.json:
        payload = {
            "schema_version": 1,
            "targets": [
                {
                    "target_id": record.target_id,
                    "display_name": record.display_name,
                    "aliases": list(record.aliases),
                    "default": record.is_default,
                }
                for record in records
            ],
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
        return 0
    print("external target 별칭")
    if not records:
        print("- 대상 없음")
        return 0
    for record in records:
        aliases = ", ".join("@" + alias for alias in record.aliases) if record.aliases else "별칭 없음"
        default_marker = " (@default, 기본 대상)" if record.is_default else ""
        print(f"- 대상 ID `{record.target_id}`{default_marker}: {aliases}")
    return 0


def command_target_set_default(args: argparse.Namespace) -> int:
    try:
        record = harness_controller.set_default_target(repo_root(), args.target_id)
        print("target default selector 설정 완료")
        print(f"- @default -> `{record.target_id}`")
        print("- @default는 selector일 뿐이며 sidecar/Redis/signature에는 canonical target id만 사용됩니다.")
        return 0
    except harness_controller.ControllerError as exc:
        print(f"error: {exc}")
        return 2


def command_target_clear_default(args: argparse.Namespace) -> int:
    try:
        harness_controller.clear_default_target(repo_root())
        print("target default selector 제거 완료")
        print("- @default는 더 이상 해석되지 않습니다.")
        return 0
    except harness_controller.ControllerError as exc:
        print(f"error: {exc}")
        return 2


def _shim_dir(raw_prefix: Path) -> Path:
    expanded = raw_prefix.expanduser()
    return expanded if expanded.is_absolute() else (Path.cwd() / expanded).absolute()


def _path_is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
    except ValueError:
        return False
    return True


def _validate_shim_dir(prefix: Path) -> None:
    resolved_prefix = prefix.resolve()
    for unsafe in UNSAFE_GLOBAL_SHIM_DIRS:
        if resolved_prefix == unsafe or _path_is_relative_to(resolved_prefix, unsafe):
            raise HarnessCliError(f"unsafe global shim prefix: {prefix.as_posix()}")
    if prefix.exists() and prefix.is_symlink():
        raise HarnessCliError(f"refusing symlink prefix: {prefix.as_posix()}")
    if prefix.exists() and not prefix.is_dir():
        raise HarnessCliError(f"global shim prefix is not a directory: {prefix.as_posix()}")


def _global_shim_path(prefix: Path) -> Path:
    return _shim_dir(prefix) / "harness"


def _global_shim_text() -> str:
    return f"""#!/usr/bin/env python3
# {GLOBAL_SHIM_MARKER}
from __future__ import annotations

import os
import sys
from pathlib import Path

MARKER = {GLOBAL_SHIM_MARKER!r}
REQUIRED_LOCAL_FILES = (
    "HARNESS.md",
    "scripts/harness_cli.py",
    "scripts/harness_starter_install.py",
    "scripts/harness_export.py",
    "docs/harness/START_HERE.md",
)


def _is_global_shim(path: Path) -> bool:
    try:
        return MARKER in path.read_text(encoding="utf-8", errors="replace")[:4096]
    except OSError:
        return False


def _is_local_harness_root(directory: Path) -> bool:
    return all((directory / relative).exists() for relative in REQUIRED_LOCAL_FILES)


def _find_local_harness(start: Path) -> Path | None:
    for directory in (start, *start.parents):
        candidate = directory / "harness"
        if not candidate.exists() or not candidate.is_file():
            continue
        if _is_global_shim(candidate):
            continue
        if not _is_local_harness_root(directory):
            continue
        if os.access(candidate, os.X_OK):
            return candidate
    return None


def main() -> int:
    local = _find_local_harness(Path.cwd().resolve())
    if local is None:
        print("error: repo-local ./harness not found from current directory or parents", file=sys.stderr)
        return 2
    os.execv(str(local), [str(local), *sys.argv[1:]])
    return 127


if __name__ == "__main__":
    raise SystemExit(main())
"""


def _is_installed_global_shim(path: Path) -> bool:
    if not path.exists() or path.is_symlink() or not path.is_file():
        return False
    try:
        return GLOBAL_SHIM_MARKER in path.read_text(encoding="utf-8", errors="replace")[:4096]
    except OSError:
        return False


def command_self_doctor(args: argparse.Namespace) -> int:
    prefix = _shim_dir(args.prefix)
    target = prefix / "harness"
    local = repo_root() / "harness"
    print("하네스 global wrapper doctor")
    print(f"- local ./harness: {'ok' if local.exists() else 'missing'}")
    print(f"- install dir: `{prefix.as_posix()}`")
    print(f"- installed shim: {'yes' if _is_installed_global_shim(target) else 'no'}")
    print("- canonical entrypoint: repo/bundle-local `./harness`")
    print("- global wrapper role: current directory or parent repo의 `./harness`로 위임")
    return 0


def command_self_install(args: argparse.Namespace) -> int:
    prefix = _shim_dir(args.prefix)
    target = prefix / "harness"
    try:
        _validate_shim_dir(prefix)
        prefix.mkdir(parents=True, exist_ok=True)
        if target.exists() or target.is_symlink():
            if _is_installed_global_shim(target):
                print("하네스 global wrapper가 이미 설치되어 있습니다.")
                print(f"- path: `{target.as_posix()}`")
                return 0
            raise HarnessCliError(f"refusing to overwrite existing file: {target.as_posix()}")
        with target.open("x", encoding="utf-8") as handle:
            handle.write(_global_shim_text())
        target.chmod(0o755)
        print("하네스 global wrapper 설치 완료")
        print(f"- path: `{target.as_posix()}`")
        print("- shell profile 수정: no")
        print("- sudo 사용: no")
        print("다음: PATH에 이 디렉토리가 이미 있으면 harness <command>를 사용할 수 있습니다.")
        return 0
    except HarnessCliError as exc:
        print(f"error: {exc}")
        return 2


def command_self_uninstall(args: argparse.Namespace) -> int:
    target = _global_shim_path(args.prefix)
    try:
        if not target.exists():
            print("하네스 global wrapper가 설치되어 있지 않습니다.")
            print(f"- path: `{target.as_posix()}`")
            return 0
        if not _is_installed_global_shim(target):
            raise HarnessCliError(f"refusing to remove non-harness file: {target.as_posix()}")
        target.unlink()
        print("하네스 global wrapper 제거 완료")
        print(f"- path: `{target.as_posix()}`")
        return 0
    except HarnessCliError as exc:
        print(f"error: {exc}")
        return 2


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="One-command local harness starter CLI.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    new = subparsers.add_parser("new", help="Create a new git repo and install the harness starter.")
    new.add_argument("target", type=Path)
    new.add_argument("--name")
    new.add_argument("--profile", choices=harness_profiles.profile_names(), default=harness_profiles.DEFAULT_PROFILE)
    new.add_argument("--no-telegram", action="store_true")
    new.add_argument("--no-input", action="store_true", help="Use deterministic starter defaults; this is the default.")
    new.add_argument("--dry-run", action="store_true")
    new.add_argument("--force-existing", action="store_true")
    new.add_argument("--include-policy", action="store_true")
    new.add_argument("--answers", type=Path)
    new.add_argument("--no-wizard", action="store_true")
    new.set_defaults(func=command_new)

    init = subparsers.add_parser("init", help="Install the harness starter into an existing clean git repo.")
    init.add_argument("target", nargs="?", type=Path, default=Path("."))
    init.add_argument("--name")
    init.add_argument("--profile", choices=harness_profiles.profile_names(), default=harness_profiles.DEFAULT_PROFILE)
    init.add_argument("--no-telegram", action="store_true")
    init.add_argument("--no-input", action="store_true", help="Use deterministic starter defaults; this is the default.")
    init.add_argument("--dry-run", action="store_true")
    init.add_argument("--force-existing", action="store_true")
    init.add_argument("--include-policy", action="store_true")
    init.add_argument("--answers", type=Path)
    init.add_argument("--no-wizard", action="store_true")
    init.set_defaults(func=command_init)

    verify = subparsers.add_parser("verify", help="Check starter installation and operator env readiness.")
    verify.add_argument("target", nargs="?", type=Path, default=Path("."))
    verify.add_argument("--json", action="store_true", help="Emit secret-safe JSON readiness output.")
    verify.add_argument("--loop-ready", action="store_true", help="Check whether a bounded starter loop can run.")
    verify.set_defaults(func=command_verify)

    complete_setup = subparsers.add_parser("complete-setup", help="Render/apply the bootstrap wizard through ./harness.")
    complete_setup.add_argument("target", nargs="?", type=Path, default=Path("."))
    complete_setup.add_argument("--run", type=Path)
    complete_setup.add_argument("--apply", action="store_true")
    complete_setup.add_argument("--no-commit", action="store_true")
    complete_setup.add_argument("--force-existing", action="store_true")
    complete_setup.set_defaults(func=command_complete_setup)

    status = subparsers.add_parser("status", help="Delegate to scripts/harness_autonomy.py status.")
    status.add_argument("--json", action="store_true")
    status.add_argument("extra", nargs=argparse.REMAINDER)
    status.set_defaults(func=command_status)

    dashboard = subparsers.add_parser("dashboard", help="Show local operator dashboard paths.")
    dashboard.set_defaults(func=command_dashboard)

    run = subparsers.add_parser("run", help="Run a bounded one-cycle launcher smoke.")
    run.add_argument("--once", action="store_true")
    run.add_argument("extra", nargs=argparse.REMAINDER)
    run.set_defaults(func=command_run)

    export = subparsers.add_parser("export", help="Write a starter-safe bundle for installing elsewhere.")
    export.add_argument("output_dir", type=Path)
    export.add_argument("--force", action="store_true", help="Replace an existing starter bundle output directory.")
    export.set_defaults(func=command_export)

    upgrade = subparsers.add_parser("upgrade", help="Preview or apply a starter-safe harness upgrade.")
    upgrade.add_argument("target", nargs="?", type=Path, default=Path("."))
    upgrade.add_argument("--source", required=True, type=Path, help="Starter bundle or compatible source checkout.")
    upgrade.add_argument("--apply", action="store_true", help="Apply the upgrade plan.")
    upgrade.add_argument("--json", action="store_true", help="Emit secret-safe JSON upgrade plan.")
    upgrade.add_argument("--force-existing", action="store_true", help="Allow overwriting locally changed starter files.")
    upgrade.set_defaults(func=command_upgrade)

    profiles = subparsers.add_parser("profiles", help="List or show starter profiles.")
    profiles.add_argument("action", nargs="?", choices=("show",))
    profiles.add_argument("profile_name", nargs="?")
    profiles.set_defaults(func=command_profiles)

    env = subparsers.add_parser("env", help="Check external env readiness without printing secret values.")
    env_subparsers = env.add_subparsers(dest="env_command", required=True)
    env_check = env_subparsers.add_parser("check", help="Read local env readiness for an external provider.")
    env_check.add_argument("--provider", required=True, choices=harness_env.provider_names())
    env_check.add_argument("--json", action="store_true")
    env_check.set_defaults(func=command_env_check)
    env_register = env_subparsers.add_parser("register", help="Show a dry-run provider registration plan.")
    env_register.add_argument("--provider", required=True, choices=harness_env.provider_names())
    env_register.add_argument("--dry-run", action="store_true")
    env_register.add_argument("--json", action="store_true")
    env_register.set_defaults(func=command_env_register)

    version = subparsers.add_parser("version", help="Show harness version and export source readiness.")
    version.add_argument("--json", action="store_true")
    version.set_defaults(func=command_version)

    controller = subparsers.add_parser("controller", help="Inspect external harness controller readiness.")
    controller_subparsers = controller.add_subparsers(dest="controller_command", required=True)
    controller_export = controller_subparsers.add_parser("export", help="Write a controller-safe distribution bundle.")
    controller_export.add_argument("output_dir", type=Path)
    controller_export.add_argument("--force", action="store_true", help="Replace an existing controller bundle output directory.")
    controller_export.add_argument("--sanitize-report", type=Path)
    controller_export.set_defaults(func=command_controller_export)
    controller_doctor = controller_subparsers.add_parser("doctor", help="Check this checkout as a harness controller.")
    controller_doctor.add_argument("--json", action="store_true")
    controller_doctor.set_defaults(func=command_controller_doctor)

    target = subparsers.add_parser("target", help="Manage product repositories from an external harness controller.")
    target_subparsers = target.add_subparsers(dest="target_command", required=True)
    target_add = target_subparsers.add_parser("add", help="Register a local product git repo as an external target.")
    target_id_help = "canonical target id (예: my-app; latest/default/all/embedded 금지)"
    target_selector_help = "target selector: canonical id, @alias, or @default"
    target_add.add_argument("target_id", help=target_id_help)
    target_add.add_argument("--repo", required=True, type=Path)
    target_add.add_argument("--branch", default="main")
    target_add.add_argument("--profile", choices=harness_profiles.profile_names(), default=harness_profiles.DEFAULT_PROFILE)
    target_add.add_argument("--display-name", help="Operator-facing display name; canonical id remains unchanged.")
    target_add.add_argument("--force", action="store_true", help="Replace an existing local target registry entry.")
    target_add.add_argument("--json", action="store_true")
    target_add.set_defaults(func=command_target_add)
    target_list = target_subparsers.add_parser("list", help="List registered external targets.")
    target_list.add_argument("--json", action="store_true")
    target_list.set_defaults(func=command_target_list)
    target_verify = target_subparsers.add_parser("verify", help="Verify an external target without mutating product files.")
    target_verify.add_argument("target", help=target_selector_help)
    target_verify.add_argument("--json", action="store_true")
    target_verify.set_defaults(func=command_target_verify)
    target_status = target_subparsers.add_parser("status", help="Show a compact external target status.")
    target_status.add_argument("target", help=target_selector_help)
    target_status.add_argument("--json", action="store_true")
    target_status.set_defaults(func=command_target_status)
    target_dashboard = target_subparsers.add_parser("dashboard", help="Write the read-only external target dashboard.")
    target_dashboard.add_argument("target", help=target_selector_help)
    target_dashboard.add_argument("--json", action="store_true")
    target_dashboard.set_defaults(func=command_target_dashboard)
    target_run = target_subparsers.add_parser("run", help="Run an external target smoke.")
    target_run.add_argument("target", help=target_selector_help)
    target_run.add_argument("--once", action="store_true")
    target_run.add_argument("--execute-once", action="store_true", help="Explicitly create one local product diff smoke.")
    target_run.add_argument(
        "--commit",
        action="store_true",
        help=(
            "With --execute-once only, create a local unpushed smoke commit; "
            "skips hooks/GPG signing and is not a shared product commit."
        ),
    )
    target_run.add_argument(
        "--push",
        action="store_true",
        help=(
            "With --execute-once --commit only, push the smoke commit to the registered branch; "
            "externally visible, may trigger product repo push automation, not deployment, "
            "and no automatic remote rollback."
        ),
    )
    target_run.set_defaults(func=command_target_run)
    target_alias = target_subparsers.add_parser("alias", help="Manage target aliases used as explicit @selectors.")
    target_alias_subparsers = target_alias.add_subparsers(dest="target_alias_command", required=True)
    target_alias_add = target_alias_subparsers.add_parser("add", help="Add an @alias to a canonical target id.")
    target_alias_add.add_argument("target_id", help=target_id_help)
    target_alias_add.add_argument("alias", help="alias name; @ prefix is optional")
    target_alias_add.set_defaults(func=command_target_alias_add)
    target_alias_remove = target_alias_subparsers.add_parser("remove", help="Remove an @alias from a canonical target id.")
    target_alias_remove.add_argument("target_id", help=target_id_help)
    target_alias_remove.add_argument("alias", help="alias name; @ prefix is optional")
    target_alias_remove.set_defaults(func=command_target_alias_remove)
    target_alias_list = target_alias_subparsers.add_parser("list", help="List aliases for all targets.")
    target_alias_list.add_argument("--json", action="store_true")
    target_alias_list.set_defaults(func=command_target_alias_list)
    target_set_default = target_subparsers.add_parser("set-default", help="Set explicit @default selector for read-only convenience.")
    target_set_default.add_argument("target_id", help=target_id_help)
    target_set_default.set_defaults(func=command_target_set_default)
    target_clear_default = target_subparsers.add_parser("clear-default", help="Clear explicit @default selector.")
    target_clear_default.set_defaults(func=command_target_clear_default)

    self_parser = subparsers.add_parser("self", help="Install or inspect the optional global harness wrapper.")
    self_subparsers = self_parser.add_subparsers(dest="self_command", required=True)
    self_doctor = self_subparsers.add_parser("doctor", help="Inspect optional global wrapper status.")
    self_doctor.add_argument(
        "--prefix",
        type=Path,
        default=DEFAULT_GLOBAL_SHIM_DIR,
        help="User bin directory to inspect; no PATH or shell profile changes are made.",
    )
    self_doctor.set_defaults(func=command_self_doctor)
    self_install = self_subparsers.add_parser("install", help="Install a thin global wrapper into a user prefix.")
    self_install.add_argument(
        "--prefix",
        type=Path,
        default=DEFAULT_GLOBAL_SHIM_DIR,
        help="User bin directory for the wrapper; system prefixes and overwrites are refused.",
    )
    self_install.set_defaults(func=command_self_install)
    self_uninstall = self_subparsers.add_parser("uninstall", help="Remove a marked harness global wrapper.")
    self_uninstall.add_argument(
        "--prefix",
        type=Path,
        default=DEFAULT_GLOBAL_SHIM_DIR,
        help="User bin directory containing a marked harness wrapper to remove.",
    )
    self_uninstall.set_defaults(func=command_self_uninstall)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
